<template>
  <div class="container mx-auto lg:w-1/3">
    <nav class="sticky top-0 z-10">
      <div class="bg-yellow-500 justify-between flex">
        <div class="bg-yellow-400 p-4">
          <Bars3Icon class="w-6" />
        </div>
        <div class="p-4">
          <ShoppingBagIcon class="w-6" />
        </div>
      </div>
    </nav>
    <div class="px-3 pt-5">
      <!-- STORE TITLE -->
      <div class="mb-3">
        <h1 class="font-bold text-2xl">Hao Bao Wonton Noodles</h1>

        <div class="flex gap-3">
          <p class="text-gray-400">2.4km away</p>

          <p class="font-medium flex gap-1">
            <ClockIcon class="w-4 inline-block text-yellow-500" />
            <span>Delivery 45 min</span>
          </p>
        </div>
      </div>
      <!-- STORE TITLE END -->

      <!-- FILTER -->
      <div class="mb-5 flex gap-2 overflow-auto hide-scroll" id="filter-bar">
        <span
          v-if="filter != null"
          class="pl-5 pr-2 py-2 rounded-full text-sm font-medium whitespace-nowrap bg-yellow-500 flex gap-1"
          @click="filter = null"
        >
          <span>
            {{ filter.name }}
          </span>
          <span>
            <XCircleIcon class="w-5 text-yellow-700" />
          </span>
        </span>
        <span
          v-for="(category, index) in categories.filter(
            (cat) => cat.id != filter?.id
          )"
          :key="index"
          class="px-5 py-2 rounded-full text-sm font-medium whitespace-nowrap"
          :class="filter?.id === category.id ? 'bg-yellow-500' : 'bg-gray-200'"
          @click="handleFilterSelect(category)"
        >
          <span>{{ category.name }}</span>
        </span>
      </div>
      <!-- FILTER END -->
      <!-- STORE ITEMS -->
      <div class="grid grid-cols-2 gap-3 pb-20">
        <food-card v-for="item in filteredItems" :item="item" :key="item.id" />
      </div>
      <!-- STORE ITEMS END -->
    </div>
  </div>
</template>

<script>
import {
  ClockIcon,
  StarIcon as StarIconOutline,
  ShoppingBagIcon,
  Bars3Icon,
} from "@heroicons/vue/24/outline";
import { StarIcon, XCircleIcon } from "@heroicons/vue/24/solid";
import FoodCard from "./FoodCard.vue";
import * as Item from "@/api/item";
import { ref } from "@vue/reactivity";
import { computed } from "@vue/runtime-core";
export default {
  components: {
    ClockIcon,
    StarIconOutline,
    StarIcon,
    ShoppingBagIcon,
    Bars3Icon,
    XCircleIcon,
    FoodCard,
  },
  setup() {
    const items = ref([
      {
        id: 13,
        name: "Beef Wonton Mami",
        image:
          "https://preview.redd.it/d0jkal5xpou71.jpg?auto=webp&s=4429163d3f3f319eb74788326595993f39822132",
        description: null,
        price: 260,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 1,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 1,
          name: "Mami",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 14,
        name: "Beef Mami",
        image:
          "https://cookinginchinglish.com/wp-content/uploads/2019/08/beef-noodle.jpg",
        description: null,
        price: 190,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 1,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 1,
          name: "Mami",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 15,
        name: "Wonton Mami",
        image:
          "https://i2.wp.com/seonkyounglongest.com/wp-content/uploads/2018/12/Wonton-Noodle-Soup-2.jpg?fit=1300%2C732&ssl=1",
        description: null,
        price: 175,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 1,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 1,
          name: "Mami",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 16,
        name: "Wonton Soup",
        image:
          "https://www.okonomikitchen.com/wp-content/uploads/2021/02/vegan-wonton-soup-1-of-1-1024x1536.jpg",
        description: null,
        price: 125,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 1,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 1,
          name: "Mami",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 17,
        name: "Extra Noodles",
        image:
          "https://thewoksoflife.com/wp-content/uploads/2020/04/homemade-chinese-egg-noodles-19-e1609271249794.jpg",
        description: null,
        price: 50,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 1,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 1,
          name: "Mami",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 18,
        name: "4Pcs Fried Chicken",
        image:
          "https://images.unsplash.com/photo-1626082896492-766af4eb6501?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZnJpZWQlMjBjaGlja2VufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
        description: null,
        price: 260,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 2,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [
          {
            id: 2,
            name: "Flavor",
            description: null,
            limit: null,
            store_id: 1,
            created_by: 1,
            updated_by: null,
            created_at: "2023-01-12T02:23:13.000000Z",
            updated_at: "2023-01-12T02:23:13.000000Z",
            pivot: { item_id: 18, modifier_id: 2 },
            items: [
              {
                id: 7,
                name: "Classic",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 8,
                name: "Hao Bao Original",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 9,
                name: "Orange Chicken",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 10,
                name: "Honey Garlic",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 11,
                name: "Soy Garlic",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 12,
                name: "Szechuan",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
            ],
          },
        ],
        category: {
          id: 2,
          name: "Fried Chicken",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 19,
        name: "6Pcs Fried Chicken",
        image:
          "https://images.unsplash.com/photo-1626082896492-766af4eb6501?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZnJpZWQlMjBjaGlja2VufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
        description: null,
        price: 390,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 2,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [
          {
            id: 2,
            name: "Flavor",
            description: null,
            limit: null,
            store_id: 1,
            created_by: 1,
            updated_by: null,
            created_at: "2023-01-12T02:23:13.000000Z",
            updated_at: "2023-01-12T02:23:13.000000Z",
            pivot: { item_id: 19, modifier_id: 2 },
            items: [
              {
                id: 7,
                name: "Classic",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 8,
                name: "Hao Bao Original",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 9,
                name: "Orange Chicken",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 10,
                name: "Honey Garlic",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 11,
                name: "Soy Garlic",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 12,
                name: "Szechuan",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
            ],
          },
        ],
        category: {
          id: 2,
          name: "Fried Chicken",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 20,
        name: "8Pcs Fried Chicken",
        image:
          "https://images.unsplash.com/photo-1626082896492-766af4eb6501?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZnJpZWQlMjBjaGlja2VufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
        description: null,
        price: 520,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 2,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [
          {
            id: 2,
            name: "Flavor",
            description: null,
            limit: null,
            store_id: 1,
            created_by: 1,
            updated_by: null,
            created_at: "2023-01-12T02:23:13.000000Z",
            updated_at: "2023-01-12T02:23:13.000000Z",
            pivot: { item_id: 20, modifier_id: 2 },
            items: [
              {
                id: 7,
                name: "Classic",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 8,
                name: "Hao Bao Original",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 9,
                name: "Orange Chicken",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 10,
                name: "Honey Garlic",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 11,
                name: "Soy Garlic",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 12,
                name: "Szechuan",
                description: null,
                price: 0,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 2,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
            ],
          },
        ],
        category: {
          id: 2,
          name: "Fried Chicken",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 21,
        name: "Beef Brocolli",
        image:
          "https://iheartumami.com/wp-content/uploads/2017/09/Paleo-Beef-with-Broccoli-recipe.jpg",
        description: null,
        price: 285,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 3,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 3,
          name: "Family Size Entree",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 22,
        name: "Sweet & Sour Pork",
        image:
          "https://tasteasianfood.com/wp-content/uploads/2019/05/sweet-and-sour-pork-featured-image-720x540.jpg",
        description: null,
        price: 245,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 3,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 3,
          name: "Family Size Entree",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 23,
        name: "Szechuan Pork",
        image:
          "https://img.taste.com.au/dwv4TF9O/taste/2016/11/sichuan-pork-105860-1.jpeg",
        description: null,
        price: 245,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 3,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 3,
          name: "Family Size Entree",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 25,
        name: "Shanghai Rolls",
        description: null,
        price: 195,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 3,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 3,
          name: "Family Size Entree",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 26,
        name: "Stir-Fried Bok Choy",
        description: null,
        price: 195,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 3,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 3,
          name: "Family Size Entree",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 27,
        name: "Soy Garlic Spinach",
        description: null,
        price: 120,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 3,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 3,
          name: "Family Size Entree",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 28,
        name: "Shrimp Fried Rice - Platter",
        image:
          "https://www.acouplecooks.com/wp-content/uploads/2020/06/Shrimp-Fried-Rice-005.jpg",
        description: null,
        price: 360,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 4,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 4,
          name: "Fried Rice Platter",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 29,
        name: "Yang Chow - Platter",
        image:
          "https://i.pinimg.com/originals/52/3d/85/523d8513ed5169f1be18fe92bc3224cd.jpg",
        description: null,
        price: 315,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 4,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 4,
          name: "Fried Rice Platter",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 30,
        name: "Pork Chow Fan - Platter",
        image:
          "https://i0.wp.com/www.angsarap.net/wp-content/uploads/2020/04/Chao-Fan-Wide.jpg?fit=1080%2C720&ssl=1",
        description: null,
        price: 265,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 4,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 4,
          name: "Fried Rice Platter",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 31,
        name: "Hao Bao Egg Fried Rice - Platter",
        image:
          "https://www.africanbites.com/wp-content/uploads/2020/04/IMG_9812.jpg",
        description: null,
        price: 245,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 4,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [],
        category: {
          id: 4,
          name: "Fried Rice Platter",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 32,
        name: "Shrimp Egg Fried Rice - R.Bowl",
        description: null,
        price: 125,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 5,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [
          {
            id: 1,
            name: "Add-Ons",
            description: null,
            limit: null,
            store_id: 1,
            created_by: 1,
            updated_by: null,
            created_at: "2023-01-12T02:23:13.000000Z",
            updated_at: "2023-01-12T02:23:13.000000Z",
            pivot: { item_id: 32, modifier_id: 1 },
            items: [
              {
                id: 1,
                name: "Sweet & Sour Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 2,
                name: "Szechuan Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 3,
                name: "4Pcs Wonton Dumplings",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 4,
                name: "6Pcs Shanghai Rolls",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 5,
                name: "1Pc Fried Chicken",
                description: null,
                price: 65,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 6,
                name: "Fried Egg",
                description: null,
                price: 25,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
            ],
          },
        ],
        category: {
          id: 5,
          name: "Rice Bowls - Pick Your Toppings!",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 33,
        name: "Yang Chow - R.Bowl",
        description: null,
        price: 110,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 5,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [
          {
            id: 1,
            name: "Add-Ons",
            description: null,
            limit: null,
            store_id: 1,
            created_by: 1,
            updated_by: null,
            created_at: "2023-01-12T02:23:13.000000Z",
            updated_at: "2023-01-12T02:23:13.000000Z",
            pivot: { item_id: 33, modifier_id: 1 },
            items: [
              {
                id: 1,
                name: "Sweet & Sour Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 2,
                name: "Szechuan Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 3,
                name: "4Pcs Wonton Dumplings",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 4,
                name: "6Pcs Shanghai Rolls",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 5,
                name: "1Pc Fried Chicken",
                description: null,
                price: 65,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 6,
                name: "Fried Egg",
                description: null,
                price: 25,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
            ],
          },
        ],
        category: {
          id: 5,
          name: "Rice Bowls - Pick Your Toppings!",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 34,
        name: "Pork Chow Fan - R.Bowl",
        description: null,
        price: 95,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 5,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [
          {
            id: 1,
            name: "Add-Ons",
            description: null,
            limit: null,
            store_id: 1,
            created_by: 1,
            updated_by: null,
            created_at: "2023-01-12T02:23:13.000000Z",
            updated_at: "2023-01-12T02:23:13.000000Z",
            pivot: { item_id: 34, modifier_id: 1 },
            items: [
              {
                id: 1,
                name: "Sweet & Sour Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 2,
                name: "Szechuan Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 3,
                name: "4Pcs Wonton Dumplings",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 4,
                name: "6Pcs Shanghai Rolls",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 5,
                name: "1Pc Fried Chicken",
                description: null,
                price: 65,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 6,
                name: "Fried Egg",
                description: null,
                price: 25,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
            ],
          },
        ],
        category: {
          id: 5,
          name: "Rice Bowls - Pick Your Toppings!",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 35,
        name: "Hao Bao Egg Fried Rice - R.Bowl",
        description: null,
        price: 85,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 5,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [
          {
            id: 1,
            name: "Add-Ons",
            description: null,
            limit: null,
            store_id: 1,
            created_by: 1,
            updated_by: null,
            created_at: "2023-01-12T02:23:13.000000Z",
            updated_at: "2023-01-12T02:23:13.000000Z",
            pivot: { item_id: 35, modifier_id: 1 },
            items: [
              {
                id: 1,
                name: "Sweet & Sour Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 2,
                name: "Szechuan Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 3,
                name: "4Pcs Wonton Dumplings",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 4,
                name: "6Pcs Shanghai Rolls",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 5,
                name: "1Pc Fried Chicken",
                description: null,
                price: 65,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 6,
                name: "Fried Egg",
                description: null,
                price: 25,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
            ],
          },
        ],
        category: {
          id: 5,
          name: "Rice Bowls - Pick Your Toppings!",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 36,
        name: "Shrimp Chow Mein - R.Bowl",
        description: null,
        price: 130,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 6,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [
          {
            id: 1,
            name: "Add-Ons",
            description: null,
            limit: null,
            store_id: 1,
            created_by: 1,
            updated_by: null,
            created_at: "2023-01-12T02:23:13.000000Z",
            updated_at: "2023-01-12T02:23:13.000000Z",
            pivot: { item_id: 36, modifier_id: 1 },
            items: [
              {
                id: 1,
                name: "Sweet & Sour Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 2,
                name: "Szechuan Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 3,
                name: "4Pcs Wonton Dumplings",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 4,
                name: "6Pcs Shanghai Rolls",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 5,
                name: "1Pc Fried Chicken",
                description: null,
                price: 65,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 6,
                name: "Fried Egg",
                description: null,
                price: 25,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
            ],
          },
        ],
        category: {
          id: 6,
          name: "Chow Mein Bowls - Pick Your Toppings!",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 37,
        name: "Beef Chow Mein - C.Bowl",
        description: null,
        price: 115,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 6,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [
          {
            id: 1,
            name: "Add-Ons",
            description: null,
            limit: null,
            store_id: 1,
            created_by: 1,
            updated_by: null,
            created_at: "2023-01-12T02:23:13.000000Z",
            updated_at: "2023-01-12T02:23:13.000000Z",
            pivot: { item_id: 37, modifier_id: 1 },
            items: [
              {
                id: 1,
                name: "Sweet & Sour Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 2,
                name: "Szechuan Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 3,
                name: "4Pcs Wonton Dumplings",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 4,
                name: "6Pcs Shanghai Rolls",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 5,
                name: "1Pc Fried Chicken",
                description: null,
                price: 65,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 6,
                name: "Fried Egg",
                description: null,
                price: 25,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
            ],
          },
        ],
        category: {
          id: 6,
          name: "Chow Mein Bowls - Pick Your Toppings!",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 38,
        name: "Pork Chow Mein - C.Bowl",
        description: null,
        price: 105,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 6,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [
          {
            id: 1,
            name: "Add-Ons",
            description: null,
            limit: null,
            store_id: 1,
            created_by: 1,
            updated_by: null,
            created_at: "2023-01-12T02:23:13.000000Z",
            updated_at: "2023-01-12T02:23:13.000000Z",
            pivot: { item_id: 38, modifier_id: 1 },
            items: [
              {
                id: 1,
                name: "Sweet & Sour Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 2,
                name: "Szechuan Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 3,
                name: "4Pcs Wonton Dumplings",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 4,
                name: "6Pcs Shanghai Rolls",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 5,
                name: "1Pc Fried Chicken",
                description: null,
                price: 65,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 6,
                name: "Fried Egg",
                description: null,
                price: 25,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
            ],
          },
        ],
        category: {
          id: 6,
          name: "Chow Mein Bowls - Pick Your Toppings!",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
      {
        id: 39,
        name: "Vegetable Chow Mein - C.Bowl",
        description: null,
        price: 105,
        cost: null,
        stock: null,
        low_stock_threshold: null,
        track_stock: false,
        sell: true,
        modifier_id: null,
        store_id: 1,
        parent_id: null,
        category_id: 6,
        created_by: 1,
        updated_by: null,
        created_at: "2023-01-12T02:23:13.000000Z",
        updated_at: "2023-01-12T02:23:13.000000Z",
        modifiers: [
          {
            id: 1,
            name: "Add-Ons",
            description: null,
            limit: null,
            store_id: 1,
            created_by: 1,
            updated_by: null,
            created_at: "2023-01-12T02:23:13.000000Z",
            updated_at: "2023-01-12T02:23:13.000000Z",
            pivot: { item_id: 39, modifier_id: 1 },
            items: [
              {
                id: 1,
                name: "Sweet & Sour Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 2,
                name: "Szechuan Pork",
                description: null,
                price: 85,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 3,
                name: "4Pcs Wonton Dumplings",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 4,
                name: "6Pcs Shanghai Rolls",
                description: null,
                price: 80,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 5,
                name: "1Pc Fried Chicken",
                description: null,
                price: 65,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
              {
                id: 6,
                name: "Fried Egg",
                description: null,
                price: 25,
                cost: null,
                stock: null,
                low_stock_threshold: null,
                track_stock: false,
                sell: true,
                modifier_id: 1,
                store_id: 1,
                parent_id: null,
                category_id: null,
                created_by: 1,
                updated_by: null,
                created_at: "2023-01-12T02:23:13.000000Z",
                updated_at: "2023-01-12T02:23:13.000000Z",
              },
            ],
          },
        ],
        category: {
          id: 6,
          name: "Chow Mein Bowls - Pick Your Toppings!",
          description: null,
          store_id: 1,
          created_by: 1,
          updated_by: null,
          created_at: "2023-01-12T02:23:13.000000Z",
          updated_at: "2023-01-12T02:23:13.000000Z",
        },
      },
    ]);

    const loading = ref(false);

    loading.value = true;

    const filter = ref(null);
    const filterBar = ref(null);

    const categories = computed(() => {
      let _categories = [];

      items.value.forEach((item) => {
        if (
          item.category &&
          _categories.find((_cat) => _cat.id === item.category.id) === undefined
        ) {
          _categories.push(item.category);
        }
      });

      return _categories;
    });

    const filteredItems = computed(() => {
      if (filter.value === null) {
        return items.value.sort((a, b) => {
          return b.price - a.price;
        });
      }

      return items.value.filter(
        (item) => item.category?.id === filter.value.id
      );
    });

    const handleFilterSelect = (cat) => {
      filter.value = cat;

      document.querySelector("#filter-bar").scrollTo({
        left: 0,
        behavior: "smooth",
      });
    };

    // Item.index(1)
    //   .then((response) => {
    //     if (response.status === 200) {
    //       items.value = response.data.data;
    //       localStorage.setItem("items", JSON.stringify(items.value));
    //     }
    //   })
    //   .finally(() => {
    //     loading.value = false;
    //   });

    return {
      items,
      filteredItems,
      categories,
      filter,
      handleFilterSelect,
    };
  },
};
</script>

<style></style>
